# Generated by Django 3.1.6 on 2021-02-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20210219_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
    ]
